theme: jekyll-theme-cayman

# --- Required options --- #

# Name of website
title: SwiftPackage

# --- Colours / background image --- #

# Alternatively, the navbar, footer, and page background can be set to an image
# instead of colour

navbar-img: "https://iwill.im/images/ExCodable-1920x500.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# For any extra visual customization, you can include additional CSS files in every page on your site. List any custom CSS files here
#site-css:
#  - "/assets/css/custom-styles.css"

# If you have common JavaScript files that should be included in every page, list them here
#site-js:
#  - "/assets/js/custom-script.js"

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189

