name: Generate snake game from github contribution grid
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: dd
          utcOffset: "+08:00"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%a')"
      - name: generate github-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-black.svg?color_snake=black
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-${{ env.action_state }}.svg?color_snake=${{ env.action_state }}
            dist/github-snake-${{ steps.current-time.outputs.formattedTime }}.svg?color_snake=white
            dist/github-snake-${{ steps.date.outputs.date }}.svg?color_snake=magenta
      - name: push github-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
